services:
  db:
    image: postgres:15
    container_name: postgres_gorm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mahasiswa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  go_app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db